/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sms;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import static sms.SMS.rs;
import static sms.SMS.stmt;

/**
 *
 * @author JOSE BOSS
 */
public class adminmenu extends javax.swing.JFrame {

    private int a;
    private String input;

    /**
     * Creates new form adminmenu
     */
    public adminmenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructzor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        jButton4.setText("jButton4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("ADMIN MENU");

        jButton2.setText("Modify Student Info");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Add New Student");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText("Remove Student");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("View Student Info");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Student List");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(66, 66, 66))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            SMS.sid=JOptionPane.showInputDialog("Enter Student ID","").toUpperCase();
            if(SMS.sid!=null)
            {
                rs=stmt.executeQuery("select count(sid) from student where sid='"+SMS.sid+"'");
                rs.next();
                if(rs.getInt(1)==1)
                    new modinfo().setVisible(true);
                else
                    JOptionPane.showMessageDialog(null,"Invalid ID","",JOptionPane.WARNING_MESSAGE);
            }
                
        } catch (SQLException ex) {
            //Logger.getLogger(adminmenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new login().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            //int s=SMS.specify();
            input=JOptionPane.showInputDialog("Enter Student ID","").toUpperCase();
            if(input!=null)
            {
                rs=stmt.executeQuery("select count(sid) from student where sid='"+input+"'");
                rs.next();
                if(rs.getInt(1)==1)
                {
                    SMS.rs=SMS.stmt.executeQuery("select sid,name,to_char(dob,'DD-MM-YYYY'),gender,phoneno,address,coursename,student.coursecode,cgpa,password,email,emgyno from student,course where sid='"+input+"' and course.coursecode=student.coursecode");
                    SMS.rs.next();

                    String result="\nStudent ID: "+SMS.rs.getString(1)+"\nName: "+SMS.rs.getString(2)+"\nDate of Birth: "+SMS.rs.getString(3)+"\nGender: "+SMS.rs.getString(4)+"\nPhone No.: "+SMS.rs.getString(5)+"\nEmail ID: "+SMS.rs.getString("email")+"\nEmergency Contact: "+SMS.rs.getString("emgyno")+"\nAddress: "+SMS.rs.getString(6)+"\nCourse: "+SMS.rs.getString(7)+" ("+SMS.rs.getString(8)+")"+"\nCGPA: "+SMS.rs.getFloat(9)+"\nPassword: "+SMS.rs.getString(10);
                    JOptionPane.showMessageDialog(null,result,"STUDENT INFO",JOptionPane.PLAIN_MESSAGE);
                }
                else
                    JOptionPane.showMessageDialog(null,"Invalid ID","",JOptionPane.WARNING_MESSAGE);
            }
            
       
            
        } catch (Exception ex) {
            //Logger.getLogger(studentmenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    //view student info code
//      private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
//        // TODO add your handling code here:
//         try {
//            // TODO add your handling code here:
//            //int s=SMS.specify();
//            input=JOptionPane.showInputDialog("Enter Student ID","").toUpperCase();
//            if(input!=null)
//            {
//                rs=stmt.executeQuery("select count(sid) from student where sid='"+input+"'");
//                rs.next();
//                if(rs.getInt(1)==1)
//                {
//                    SMS.rs=SMS.stmt.executeQuery("select sid,name,to_char(dob,'DD-MM-YYYY'),gender,phoneno,address,coursename,student.coursecode,cgpa,password,email,emgyno from student,course where sid='"+input+"' and course.coursecode=student.coursecode");
//                    SMS.rs.next();
//
//                    String result="\nStudent ID: "+SMS.rs.getString(1)+"\nName: "+SMS.rs.getString(2)+"\nDate of Birth: "+SMS.rs.getString(3)+"\nGender: "+SMS.rs.getString(4)+"\nPhone No.: "+SMS.rs.getString(5)+"\nEmail ID: "+SMS.rs.getString("email")+"\nEmergency Contact: "+SMS.rs.getString("emgyno")+"\nAddress: "+SMS.rs.getString(6)+"\nCourse: "+SMS.rs.getString(7)+" ("+SMS.rs.getString(8)+")"+"\nCGPA: "+SMS.rs.getFloat(9)+"\nPassword: "+SMS.rs.getString(10);
//                    JOptionPane.showMessageDialog(null,result,"STUDENT INFO",JOptionPane.PLAIN_MESSAGE);
//                }
//                else
//                    JOptionPane.showMessageDialog(null,"Invalid ID","",JOptionPane.WARNING_MESSAGE);
//            }
//            
//       
//            
//        } catch (Exception ex) {
//            //Logger.getLogger(studentmenu.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }        
    
    
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new addnewstud().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            // TODO add your handling code here:
            input=JOptionPane.showInputDialog("Enter Student ID","").toUpperCase();
            if(input!=null)
            {
                rs=stmt.executeQuery("select count(sid) from student where sid='"+input+"'");
                rs.next();
                a=rs.getInt(1);
                if(a==1)
                {
                    int b=JOptionPane.showConfirmDialog(null,"Do you want to proceed?");
                    if(b==0)
                    {

                        stmt.executeUpdate("delete from student where sid='"+input+"'");
                        if(stmt.getUpdateCount()>0)
                        {
                            stmt.executeUpdate("delete from writes_exam where sid='"+input+"'");
                            stmt.executeUpdate("delete from attends_subject where sid='"+input+"'");
                            JOptionPane.showMessageDialog(null,"Removed");
                        }
                            
                            
                    }
                }
                else
                    JOptionPane.showMessageDialog(null,"Invalid ID","",JOptionPane.WARNING_MESSAGE);
            }
                
        } catch (SQLException ex) {
            //Logger.getLogger(adminmenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            //SMS.rs=SMS.stmt.executeQuery("select * from student order by sid");
            SMS.rs=SMS.stmt.executeQuery("select sid,name,to_char(dob,'DD-MM-YYYY') as DOB,gender,phoneno,email,emgyno as EMERGENCY,address,coursename,student.coursecode,cgpa,password from student,course where course.coursecode=student.coursecode order by sid");
            
            SMS.disptable(SMS.rs);
        } catch (SQLException ex) {
            //Logger.getLogger(teachermenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminmenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
