/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sms;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import static sms.SMS.rs;
import static sms.SMS.stmt;

/**
 *
 * @author JOSE BOSS
 */
public class hodmenu extends javax.swing.JFrame {

    /**
     * Creates new form teachermenu
     */
 
    public static String sid,sub,subid,exam,coursecode,coursename;
    private String input;
    public hodmenu() {
        try {
            initComponents();
            SMS.rs=SMS.stmt.executeQuery("select subcode,subname from Subject where tid='"+SMS.uid+"'");
            SMS.rs.next();
            subid=SMS.rs.getString(1);
            sub=SMS.rs.getString(2);
            SMS.rs=SMS.stmt.executeQuery("select coursecode,coursename from Course where hod='"+SMS.uid+"'");
            SMS.rs.next();
            coursecode=SMS.rs.getString(1);
            coursename=SMS.rs.getString(2);
            course.setText(coursename+" ("+coursecode+")");
            //subname.setText
        } catch (SQLException ex) {
            Logger.getLogger(teachermenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        studlist = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        course = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("HOD MENU");

        studlist.setText("Student List");
        studlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studlistActionPerformed(evt);
            }
        });

        jButton2.setText("Marks");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Attendance");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("COURSE");

        course.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(course, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel1)))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studlist, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(124, 124, 124))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jButton1)
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(course))
                .addGap(39, 39, 39)
                .addComponent(studlist, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new login().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void studlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studlistActionPerformed
        try {
            // TODO add your handling code here:
            SMS.rs=SMS.stmt.executeQuery("select sid,name,to_char(dob,'DD-MM-YYYY') as DOB,gender,phoneno,email,emgyno,address,cgpa,password from student where coursecode=(select coursecode from course where hod='"+SMS.uid+"') order by sid");
            SMS.disptable(SMS.rs);
        } catch (SQLException ex) {
            //Logger.getLogger(teachermenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_studlistActionPerformed

    int hodcheck_sid(String sid,String uid) throws SQLException
    {
        rs=stmt.executeQuery("select count(sid) from Student where sid='"+sid+"' and coursecode=(select coursecode from course where hod='"+uid+"')");
        rs.next();
        return rs.getInt(1);
    }
    
    private void tviewmarks(String subject) {                                           
        try {
            // TODO add your handling code here:
            exam=SMS.exammenu();
            int r=SMS.specify();
            if(r==0)
            {
                SMS.sid=JOptionPane.showInputDialog("Enter Student ID","").toUpperCase();
                int a=hodcheck_sid(SMS.sid,SMS.uid);
                if(a==1)
                {
                    SMS.rs=SMS.stmt.executeQuery("select student.sid,name,marks from student,subject,exam,writes_exam where subject.subname='"+subject+"' and student.sid=writes_exam.sid and student.sid='"+SMS.sid+"' and exam.examname='"+exam+"' and exam.examid=writes_exam.examid and exam.subcode=subject.subcode");     
                    SMS.disptable(SMS.rs);
                }
                else
                    JOptionPane.showMessageDialog(null,"Invalid Student ID","",JOptionPane.WARNING_MESSAGE);
                
            }
            else 
            {
                SMS.rs=SMS.stmt.executeQuery("select Student.sid, name,marks from Student,subject,exam,writes_exam where Student.sid=writes_exam.sid and subject.subname='"+subject+"' and exam.examname='"+exam+"' and exam.examid=writes_exam.examid and exam.subcode=subject.subcode ORDER BY SID");
                SMS.disptable(SMS.rs);
            }
        } catch (Exception ex) {
            //Logger.getLogger(teachermenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                          

                                          

    private void tviewatt(String subject) {                                         
        try {
            // TODO add your handling code here:
            int r=SMS.specify();
            if(r==0)
            {
                SMS.sid=JOptionPane.showInputDialog("Enter Student ID","").toUpperCase();
                int a=hodcheck_sid(SMS.sid,SMS.uid);
                if(a==1)
                {
                    rs=stmt.executeQuery("select subcode from subject where subname='"+subject+"'");
                    rs.next();
                    subid=rs.getString(1);
                    SMS.rs=SMS.stmt.executeQuery("select student.sid,name,attpercent,abovethreshold from student,attends_subject where student.sid=attends_subject.sid and student.sid='"+SMS.sid+"' and attends_subject.subcode='"+subid+"'");
                    SMS.disptable(SMS.rs);
                }
                else
                    JOptionPane.showMessageDialog(null,"Invalid Student ID","",JOptionPane.WARNING_MESSAGE);
                
            }
            else 
            {
                SMS.rs=SMS.stmt.executeQuery("select student.sid,name,attpercent,abovethreshold from student,attends_subject where student.sid=attends_subject.sid and attends_subject.subcode='"+subid+"'");
                SMS.disptable(SMS.rs);
            }
        } catch (Exception ex) {
           // Logger.getLogger(teachermenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                        

    private void modatt(String subject) {                                       
        try {
            // TODO add your handling code here:
            String thr;
            SMS.sid=JOptionPane.showInputDialog("Enter Student ID","").toUpperCase();
            int a=hodcheck_sid(SMS.sid,SMS.uid);
            if(a==1)
            {
                rs=stmt.executeQuery("select subcode from subject where subname='"+subject+"'");
                rs.next();
                subid=rs.getString(1);
                String num=JOptionPane.showInputDialog("Enter new attendance percent","");
                int att=Integer.parseInt(num);
                if(SMS.checkatt(att)==1)
                {
                    thr=SMS.checkthr(att);
                    SMS.stmt.executeUpdate("update attends_subject set attpercent="+num+",abovethreshold='"+thr+"' where sid='"+SMS.sid+"' and subcode='"+subid+"'"); 
                    if(SMS.stmt.getUpdateCount()>0)
                        JOptionPane.showMessageDialog(null,"Attendance Updated");
                }
                else
                    JOptionPane.showMessageDialog(null,"Invalid Attendance","",JOptionPane.WARNING_MESSAGE);
           
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Invalid Student ID","",JOptionPane.WARNING_MESSAGE);
            }
        } catch (SQLException ex) {
            //Logger.getLogger(teachermenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            //Logger.getLogger(teachermenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                      

    
    
    private void modifymark(String subject) {                                           
        try {
            // TODO add your handling code here:
            SMS.sid=JOptionPane.showInputDialog("Enter Student ID","").toUpperCase();
            int a=hodcheck_sid(SMS.sid,SMS.uid);
            if(a==1)
            {
                exam=SMS.exammenu();
                int num=Integer.parseInt(JOptionPane.showInputDialog("Enter new marks",""));
                int max=SMS.getmax(exam);
                if(num>=0 & num<=max)
                {
                    rs=stmt.executeQuery("select subcode from subject where subname='"+subject+"'");
                    rs.next();
                    subid=rs.getString(1);
                    
                    SMS.stmt.executeUpdate("update writes_exam set marks="+num+" where sid='"+SMS.sid+"' and examid=(select examid from exam where subcode='"+subid+"' and examname='"+exam+"')");
                    
                    
                    if(SMS.stmt.getUpdateCount()>0)
                    {
                        float cgpa=SMS.calc_cgpa(SMS.sid);
                        //System.out.println(cgpa);
                        SMS.stmt.executeUpdate("update Student set cgpa='"+cgpa+"' where sid='"+SMS.sid+"'");
                        SMS.rs=SMS.stmt.executeQuery("select cgpa from student where sid='"+SMS.sid+"'");
                        SMS.rs.next();
                        cgpa=SMS.rs.getFloat(1);
                        JOptionPane.showMessageDialog(null,"Marks Updated. New CGPA: "+cgpa);
                    }
                        //JOptionPane.showMessageDialog(null,"Marks Updated");
                        
                    
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Invalid Marks","",JOptionPane.WARNING_MESSAGE);
                }
                    
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Invalid Student ID","",JOptionPane.WARNING_MESSAGE);
            }
        } catch (SQLException ex) {
           // Logger.getLogger(teachermenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            //Logger.getLogger(teachermenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }          
    
    
    public static String submenu() throws Exception
    {
        int i,r,a;
        rs=stmt.executeQuery("select count(subcode) from course_subject where coursecode='"+coursecode+"'");
        rs.next();
        a=rs.getInt(1);
        String[] options=new String[a];
        //initialize();
        rs=stmt.executeQuery("select subname from subject where subcode in (select subcode from course_subject where coursecode='"+coursecode+"')");
        //rs.next();
        for(i=0;rs.next();i++)
        {
            //arr[i]=rs.getString(1);
            //System.out.println(i+". "+rs.getString(1));
            options[i]=rs.getString(1);
            //System.out.println("rs.getString(1)");
        }

        r = JOptionPane.showOptionDialog(null, "Choose the subject", "",
            JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE,
            null, options, options[0]);
        
        return options[r];
    }
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            String[] options=new String[]{"View","Modify"};
            int r = JOptionPane.showOptionDialog(null, "Choose the option", "MARKS",
                    JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE,
                    null, options, options[0]);
             
            if(r==0 || r==1)
            {
                String s=submenu();
                if(s!=null)
                {
                    if(r==0)
                        tviewmarks(s);
                    else if(r==1)
                        modifymark(s);
                }
                    
            }
                
        } catch (Exception ex) {
          //  Logger.getLogger(hodmenu.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            // TODO add your handling code here:
            String[] options=new String[]{"View","Modify"};
            int r = JOptionPane.showOptionDialog(null, "Choose the option", "ATTENDANCE",
                    JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE,
                    null, options, options[0]);
            if(r==0 || r==1)
            {
                String s=submenu();
                if(s!=null)
                {
                    if(r==0)
                        tviewatt(s);
                    else if(r==1)
                        modatt(s);
                }
                    
            }
                
        } catch (Exception ex) {
           // Logger.getLogger(hodmenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teachermenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teachermenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teachermenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teachermenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teachermenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel course;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton studlist;
    // End of variables declaration//GEN-END:variables
}
